apiVersion: v1
kind: Service
metadata:
  name: node-api-service
  labels:
    app: node-api
spec:
  type: LoadBalancer # RESTORED: This exposes the service externally
  selector:
    app: node-api
  ports:
    - name: web
      protocol: TCP
      port: 4000       # Port for Postman: http://localhost:4000
      targetPort: 4000 # Matches the containerPort in your deployment