apiVersion: v1
kind: Service
metadata:
  name: node-api-service
  labels:
    app: node-api
spec:
  selector:
    app: node-api
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP